### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [stickyPiston/notifier#1]
Hi @stickyPiston , I contribute by designing logos for the open source community. I desgined a functional logo for the repo. What do you think? I will wait for feedback. Have a nice day!

![notifier](https://user-images.githubusercontent.com/36298335/58269383-19048500-7d90-11e9-9800-e003828f53f8.jpg)

**Comment by stickyPiston** [comment]
Dear @reallinfo , I think the logo design is lovely. The idea is simple but very functional, and I didn't even expect a logo in the first place, so this is a big surprise. Just a quick question. Am I allowed to use this logo in my repository and if I am, what conditions apply?

**Comment by reallinfo** [comment]
Thanks, of course! You can use it under [cc by license](https://creativecommons.org/licenses/by/4.0/).

**Comment by reallinfo** [comment]
Can I just ask you for something? Want to use any license for the repo? I will send a pr, don't worry, just a suggestion.

Maybe this can help. 

https://help.github.com/en/articles/licensing-a-repository

**Comment by stickyPiston** [comment]
Thanks for the license suggestion, I've added one too. I've also merged your Pull Request. Thanks again for the logo!

**Comment by reallinfo** [comment]
Thanks! If you need a logo for other projects, feel free to contact me. Have a nice day!
